package com.jobstream.domain;

import java.util.UUID;

/**
 * Normalized job offer produced by any job provider adapter.
 * Framework-free domain model.
 *
 * @param id          local identifier, generated by the adapter at mapping time
 * @param externalId  provider-side identifier
 * @param provider    source provider
 * @param title       job title
 * @param company     hiring company
 * @param url         link to the original job posting
 * @param description free-text description, may be null
 */
public record JobOffer(UUID id, String externalId, Provider provider, String title,
		String company, String url, String description) {
}
